/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommandsRouteImport } from './routes/commands'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NodesIndexRouteImport } from './routes/nodes.index'
import { Route as NodesNodeIdRouteImport } from './routes/nodes.$nodeId'
import { Route as ApiPublicAgentCommandsRouteImport } from './routes/api/public/agent/commands'
import { Route as ApiPublicAgentEnrollRouteImport } from './routes/api/public/agent/enroll'
import { Route as ApiPublicAgentHeartbeatRouteImport } from './routes/api/public/agent/heartbeat'
import { Route as ApiPublicCronAvailabilityRouteImport } from './routes/api/public/cron/availability'
import { Route as ApiPublicPrometheusTargetsRouteImport } from './routes/api/public/prometheus/targets'
import { Route as ApiPublicAgentCommandsCommandIdResultRouteImport } from './routes/api/public/agent/commands.$commandId.result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandsRoute = CommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIndexRoute = NodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesNodeIdRoute = NodesNodeIdRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentCommandsRoute = ApiPublicAgentCommandsRouteImport.update({
  id: '/api/public/agent/commands',
  path: '/api/public/agent/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentEnrollRoute = ApiPublicAgentEnrollRouteImport.update({
  id: '/api/public/agent/enroll',
  path: '/api/public/agent/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentHeartbeatRoute = ApiPublicAgentHeartbeatRouteImport.update({
  id: '/api/public/agent/heartbeat',
  path: '/api/public/agent/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronAvailabilityRoute =
  ApiPublicCronAvailabilityRouteImport.update({
    id: '/api/public/cron/availability',
    path: '/api/public/cron/availability',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPrometheusTargetsRoute =
  ApiPublicPrometheusTargetsRouteImport.update({
    id: '/api/public/prometheus/targets',
    path: '/api/public/prometheus/targets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentCommandsCommandIdResultRoute =
  ApiPublicAgentCommandsCommandIdResultRouteImport.update({
    id: '/$commandId/result',
    path: '/$commandId/result',
    getParentRoute: () => ApiPublicAgentCommandsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/commands': typeof CommandsRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/nodes/': typeof NodesIndexRoute
  '/api/public/agent/commands': typeof ApiPublicAgentCommandsRouteWithChildren
  '/api/public/agent/enroll': typeof ApiPublicAgentEnrollRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/cron/availability': typeof ApiPublicCronAvailabilityRoute
  '/api/public/prometheus/targets': typeof ApiPublicPrometheusTargetsRoute
  '/api/public/agent/commands/$commandId/result': typeof ApiPublicAgentCommandsCommandIdResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/commands': typeof CommandsRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/nodes': typeof NodesIndexRoute
  '/api/public/agent/commands': typeof ApiPublicAgentCommandsRouteWithChildren
  '/api/public/agent/enroll': typeof ApiPublicAgentEnrollRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/cron/availability': typeof ApiPublicCronAvailabilityRoute
  '/api/public/prometheus/targets': typeof ApiPublicPrometheusTargetsRoute
  '/api/public/agent/commands/$commandId/result': typeof ApiPublicAgentCommandsCommandIdResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/commands': typeof CommandsRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/nodes/': typeof NodesIndexRoute
  '/api/public/agent/commands': typeof ApiPublicAgentCommandsRouteWithChildren
  '/api/public/agent/enroll': typeof ApiPublicAgentEnrollRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/cron/availability': typeof ApiPublicCronAvailabilityRoute
  '/api/public/prometheus/targets': typeof ApiPublicPrometheusTargetsRoute
  '/api/public/agent/commands/$commandId/result': typeof ApiPublicAgentCommandsCommandIdResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/audit'
    | '/auth'
    | '/commands'
    | '/observability'
    | '/settings'
    | '/nodes/$nodeId'
    | '/nodes/'
    | '/api/public/agent/commands'
    | '/api/public/agent/enroll'
    | '/api/public/agent/heartbeat'
    | '/api/public/cron/availability'
    | '/api/public/prometheus/targets'
    | '/api/public/agent/commands/$commandId/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/audit'
    | '/auth'
    | '/commands'
    | '/observability'
    | '/settings'
    | '/nodes/$nodeId'
    | '/nodes'
    | '/api/public/agent/commands'
    | '/api/public/agent/enroll'
    | '/api/public/agent/heartbeat'
    | '/api/public/cron/availability'
    | '/api/public/prometheus/targets'
    | '/api/public/agent/commands/$commandId/result'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/audit'
    | '/auth'
    | '/commands'
    | '/observability'
    | '/settings'
    | '/nodes/$nodeId'
    | '/nodes/'
    | '/api/public/agent/commands'
    | '/api/public/agent/enroll'
    | '/api/public/agent/heartbeat'
    | '/api/public/cron/availability'
    | '/api/public/prometheus/targets'
    | '/api/public/agent/commands/$commandId/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  CommandsRoute: typeof CommandsRoute
  ObservabilityRoute: typeof ObservabilityRoute
  SettingsRoute: typeof SettingsRoute
  NodesNodeIdRoute: typeof NodesNodeIdRoute
  NodesIndexRoute: typeof NodesIndexRoute
  ApiPublicAgentCommandsRoute: typeof ApiPublicAgentCommandsRouteWithChildren
  ApiPublicAgentEnrollRoute: typeof ApiPublicAgentEnrollRoute
  ApiPublicAgentHeartbeatRoute: typeof ApiPublicAgentHeartbeatRoute
  ApiPublicCronAvailabilityRoute: typeof ApiPublicCronAvailabilityRoute
  ApiPublicPrometheusTargetsRoute: typeof ApiPublicPrometheusTargetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commands': {
      id: '/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof CommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/': {
      id: '/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof NodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/$nodeId': {
      id: '/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/nodes/$nodeId'
      preLoaderRoute: typeof NodesNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/commands': {
      id: '/api/public/agent/commands'
      path: '/api/public/agent/commands'
      fullPath: '/api/public/agent/commands'
      preLoaderRoute: typeof ApiPublicAgentCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/enroll': {
      id: '/api/public/agent/enroll'
      path: '/api/public/agent/enroll'
      fullPath: '/api/public/agent/enroll'
      preLoaderRoute: typeof ApiPublicAgentEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/heartbeat': {
      id: '/api/public/agent/heartbeat'
      path: '/api/public/agent/heartbeat'
      fullPath: '/api/public/agent/heartbeat'
      preLoaderRoute: typeof ApiPublicAgentHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/availability': {
      id: '/api/public/cron/availability'
      path: '/api/public/cron/availability'
      fullPath: '/api/public/cron/availability'
      preLoaderRoute: typeof ApiPublicCronAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/prometheus/targets': {
      id: '/api/public/prometheus/targets'
      path: '/api/public/prometheus/targets'
      fullPath: '/api/public/prometheus/targets'
      preLoaderRoute: typeof ApiPublicPrometheusTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/commands/$commandId/result': {
      id: '/api/public/agent/commands/$commandId/result'
      path: '/$commandId/result'
      fullPath: '/api/public/agent/commands/$commandId/result'
      preLoaderRoute: typeof ApiPublicAgentCommandsCommandIdResultRouteImport
      parentRoute: typeof ApiPublicAgentCommandsRoute
    }
  }
}

interface ApiPublicAgentCommandsRouteChildren {
  ApiPublicAgentCommandsCommandIdResultRoute: typeof ApiPublicAgentCommandsCommandIdResultRoute
}

const ApiPublicAgentCommandsRouteChildren: ApiPublicAgentCommandsRouteChildren =
  {
    ApiPublicAgentCommandsCommandIdResultRoute:
      ApiPublicAgentCommandsCommandIdResultRoute,
  }

const ApiPublicAgentCommandsRouteWithChildren =
  ApiPublicAgentCommandsRoute._addFileChildren(
    ApiPublicAgentCommandsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  CommandsRoute: CommandsRoute,
  ObservabilityRoute: ObservabilityRoute,
  SettingsRoute: SettingsRoute,
  NodesNodeIdRoute: NodesNodeIdRoute,
  NodesIndexRoute: NodesIndexRoute,
  ApiPublicAgentCommandsRoute: ApiPublicAgentCommandsRouteWithChildren,
  ApiPublicAgentEnrollRoute: ApiPublicAgentEnrollRoute,
  ApiPublicAgentHeartbeatRoute: ApiPublicAgentHeartbeatRoute,
  ApiPublicCronAvailabilityRoute: ApiPublicCronAvailabilityRoute,
  ApiPublicPrometheusTargetsRoute: ApiPublicPrometheusTargetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
